SELECT T_ONTIME_REPORTING.FL_DATE, 
T_ONTIME_REPORTING.OP_CARRIER,
T_ONTIME_REPORTING.DEP_TIME, 
T_ONTIME_REPORTING.DEP_DELAY,
T_ONTIME_REPORTING.DEP_DELAY_GROUP,
T_ONTIME_REPORTING.ORIGIN,
T_ONTIME_REPORTING.ORIGIN_CITY_NAME,
T_ONTIME_REPORTING.DEST,
T_ONTIME_REPORTING.DEST_CITY_NAME,
T_ONTIME_REPORTING.DISTANCE,
T_ONTIME_REPORTING.CARRIER_DELAY,
T_ONTIME_REPORTING.WEATHER_DELAY,
T_ONTIME_REPORTING.NAS_DELAY,
T_ONTIME_REPORTING.SECURITY_DELAY,
T_ONTIME_REPORTING.LATE_AIRCRAFT_DELAY
FROM 
T_ONTIME_REPORTING 
WHERE 
T_ONTIME_REPORTING.DEST = 'AUS' 
AND 
T_ONTIME_REPORTING.CANCELLED = '0'
AND
T_ONTIME_REPORTING.DIVERTED = '0'
-- AND
-- T_ONTIME_REPORTING.MONTH = '7'
-- AND
-- T_ONTIME_REPORTING.DAY_OF_MONTH = '8'
